pipeline{
    agent any
    stages{
        stage("checkout the code"){
            steps{
                git 'https://github.com/akshu20791/addressbook-cicd-project'
                echo "checkout completed "
            }
        }
        stage("Compile the stage"){
            steps{
                sh 'mvn compile'
                echo 'compile is done'
            }
        }
        stage("package the project"){
            steps{
                sh 'mvn package'
            }
        }
        stage("execute the unit test cases"){
            steps{
                sh 'mvn test'
            }
        }
         stage("quality assurance of the project"){
            steps{
                sh 'mvn checkstyle:checkstyle'
            }
        }
        stage("generate the qa analysis"){
            steps{
                recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [checkStyle()]
            }
        }
        stage("deploy the project on tomcat"){
            steps{
              sh "sudo cp /var/lib/jenkins/workspace/address-book-project/target/addressbook.war /home/ubuntu/apache-tomcat-9.0.120/webapps"  
            }
            
        }
    }
}
